// src/theme/iconMap.js
//
// Circosodal draws every icon from the Pixelarticons set (pixel-art icons,
// MIT license — https://pixelarticons.com). Components still ask for icons by
// their familiar Material names (`<Icon name="home" />`); this table maps
// each to the closest Pixelarticons glyph. Add a line here when you use a new
// icon name; unknown names fall back to a plain square and log a dev warning.
// Browse the set at https://pixelarticons.com to pick replacements.

export const ICON_MAP = {
  add_circle: 'plus-box',
  add_photo_alternate: 'image-2-plus',
  admin_panel_settings: 'shield',
  arrow_back: 'arrow-left',
  arrow_forward: 'arrow-right',
  arrow_upward: 'arrow-up',
  badge: 'membercard',
  bolt: 'zap',
  calendar_today: 'calendar',
  campaign: 'megaphone',
  cancel: 'cancel',
  chat: 'message',
  check: 'check',
  check_circle: 'checkbox-on',
  chevron_right: 'chevron-right',
  close: 'close',
  dark_mode: 'moon',
  dashboard: 'layout',
  delete: 'trash',
  description: 'file-text',
  edit: 'pencil',
  event: 'calendar-text',
  event_available: 'calendar-2',
  expand_more: 'chevron-down',
  explore: 'compass',
  favorite: 'heart',
  forum: 'message-text',
  gpp_maybe: 'warning-diamond',
  group: 'users',
  groups: 'users',
  history: 'clock',
  home: 'home',
  hourglass_top: 'hourglass',
  how_to_reg: 'user-plus',
  inbox: 'inbox',
  info: 'info-box',
  light_mode: 'sun',
  link_off: 'unlink',
  local_fire_department: 'fire',
  location_on: 'map-pin',
  lock: 'lock',
  lock_reset: 'refresh',
  login: 'login',
  logout: 'logout',
  mail: 'mail',
  manage_accounts: 'user',
  map: 'map',
  more_vert: 'more-vertical',
  newspaper: 'article',
  notifications: 'bell',
  open_in_new: 'external-link',
  palette: 'colors-swatch',
  person: 'user',
  photo_camera: 'camera',
  photo_library: 'images',
  pin_drop: 'map-pin',
  privacy_tip: 'shield',
  progress_activity: 'loader',
  public: 'globe',
  restart_alt: 'undo',
  schedule: 'clock',
  school: 'teach',
  search: 'search',
  search_off: 'search',
  settings: 'settings-cog',
  share: 'share',
  shield: 'shield',
  shield_person: 'shield',
  star: 'star',
  storefront: 'store',
  verified: 'check-double',
  visibility: 'eye',
  work: 'briefcase',
};

export const FALLBACK_ICON = 'square';
