-- supabase/migrations/008_discord_and_startups.sql
-- Run in the Supabase SQL Editor after 007.
--
-- Two things bundled together because they ship together: (1) linking a
-- Discord account to a Povolum account via a short-lived one-time code,
-- and (2) the startups/membership/collaboration schema the bot's
-- /create, /join, /collab, /edit commands operate on.
--
-- The bot itself connects with the SERVICE ROLE key (a trusted backend
-- process, not a browser) — it bypasses RLS entirely and does its own
-- authorization checks in code (e.g. "does this Discord user own this
-- startup?"). RLS below is still real and still matters: it's what
-- protects these same tables if/when the website ever queries them
-- directly with the anon key, and it's the ONLY thing protecting
-- connect_codes and discord_links regardless of caller.

-- ---------------------------------------------------------------------
-- profiles: opt-in discoverability for bot search. Default OFF —
-- profiles have been owner-only-visible this whole build; /search
-- shouldn't silently make every student's name/school/bio public.
-- ---------------------------------------------------------------------
alter table profiles add column if not exists discoverable boolean not null default false;

-- ---------------------------------------------------------------------
-- connect_codes: short-lived, single-use codes generated by /connect,
-- redeemed on the website. No client (not even an authenticated one)
-- should ever read or write this table directly — only the bot (service
-- role) inserts, and only the redeem_discord_connect_code() function
-- below reads/updates it, running as its own elevated context regardless
-- of who calls it.
-- ---------------------------------------------------------------------
create table if not exists connect_codes (
  code text primary key,
  discord_user_id text not null,
  discord_username text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '10 minutes'),
  used_at timestamptz
);

alter table connect_codes enable row level security;
drop policy if exists "No client access to connect_codes" on connect_codes;
create policy "No client access to connect_codes" on connect_codes for all using (false);

-- ---------------------------------------------------------------------
-- discord_links: the actual account link, one row per Povolum user.
-- ---------------------------------------------------------------------
create table if not exists discord_links (
  user_id uuid primary key references auth.users(id) on delete cascade,
  discord_user_id text not null unique,
  discord_username text,
  linked_at timestamptz not null default now()
);

alter table discord_links enable row level security;

drop policy if exists "Users read own discord link" on discord_links;
create policy "Users read own discord link" on discord_links
  for select using (auth.uid() = user_id);

drop policy if exists "Users unlink own discord" on discord_links;
create policy "Users unlink own discord" on discord_links
  for delete using (auth.uid() = user_id);
-- No insert/update policy for regular clients on purpose — the only way
-- to create or change this link is redeem_discord_connect_code() below,
-- which runs as SECURITY DEFINER and does the auth.uid() check itself.

-- ---------------------------------------------------------------------
-- redeem_discord_connect_code: the website calls this (as the signed-in
-- user, via supabase.rpc(...)) with the code shown by /connect. Validates
-- the code hasn't expired or been used, links the account, marks it used.
-- ---------------------------------------------------------------------
create or replace function public.redeem_discord_connect_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_record connect_codes%rowtype;
begin
  select * into v_record from connect_codes where code = upper(trim(p_code)) for update;

  if not found then
    return jsonb_build_object('success', false, 'error', 'Invalid code.');
  end if;
  if v_record.used_at is not null then
    return jsonb_build_object('success', false, 'error', 'That code has already been used.');
  end if;
  if v_record.expires_at < now() then
    return jsonb_build_object('success', false, 'error', 'That code has expired — run /connect again.');
  end if;

  insert into discord_links (user_id, discord_user_id, discord_username)
  values (auth.uid(), v_record.discord_user_id, v_record.discord_username)
  on conflict (user_id) do update
    set discord_user_id = excluded.discord_user_id,
        discord_username = excluded.discord_username,
        linked_at = now();

  update connect_codes set used_at = now() where code = v_record.code;

  return jsonb_build_object('success', true, 'discord_username', v_record.discord_username);
end;
$$;

revoke all on function public.redeem_discord_connect_code(text) from public;
grant execute on function public.redeem_discord_connect_code(text) to authenticated;

-- ---------------------------------------------------------------------
-- startups
-- ---------------------------------------------------------------------
create table if not exists startups (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  description text,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

alter table startups enable row level security;

drop policy if exists "Public read approved startups" on startups;
create policy "Public read approved startups" on startups
  for select using (status = 'approved');

drop policy if exists "Owners read own startups" on startups;
create policy "Owners read own startups" on startups
  for select using (owner_user_id = auth.uid());

drop policy if exists "Admins read all startups" on startups;
create policy "Admins read all startups" on startups
  for select using (is_admin());

drop policy if exists "Authenticated users create startups" on startups;
create policy "Authenticated users create startups" on startups
  for insert to authenticated with check (status = 'pending' and owner_user_id = auth.uid());

drop policy if exists "Owners update own startups" on startups;
create policy "Owners update own startups" on startups
  for update using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());

drop policy if exists "Admins moderate startups" on startups;
create policy "Admins moderate startups" on startups
  for update using (is_admin()) with check (is_admin());

-- ---------------------------------------------------------------------
-- startup_members
-- ---------------------------------------------------------------------
create table if not exists startup_members (
  id uuid primary key default uuid_generate_v4(),
  startup_id uuid not null references startups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  unique (startup_id, user_id)
);

alter table startup_members enable row level security;

drop policy if exists "Members read their own memberships" on startup_members;
create policy "Members read their own memberships" on startup_members
  for select using (user_id = auth.uid());

drop policy if exists "Owners read their startup's members" on startup_members;
create policy "Owners read their startup's members" on startup_members
  for select using (exists (select 1 from startups s where s.id = startup_members.startup_id and s.owner_user_id = auth.uid()));

-- ---------------------------------------------------------------------
-- startup_join_requests
-- ---------------------------------------------------------------------
create table if not exists startup_join_requests (
  id uuid primary key default uuid_generate_v4(),
  startup_id uuid not null references startups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  created_at timestamptz not null default now(),
  unique (startup_id, user_id)
);

alter table startup_join_requests enable row level security;

drop policy if exists "Requesters read own join requests" on startup_join_requests;
create policy "Requesters read own join requests" on startup_join_requests
  for select using (user_id = auth.uid());

drop policy if exists "Owners read join requests for their startup" on startup_join_requests;
create policy "Owners read join requests for their startup" on startup_join_requests
  for select using (exists (select 1 from startups s where s.id = startup_join_requests.startup_id and s.owner_user_id = auth.uid()));

-- ---------------------------------------------------------------------
-- startup_collaborations
-- ---------------------------------------------------------------------
create table if not exists startup_collaborations (
  id uuid primary key default uuid_generate_v4(),
  requesting_startup_id uuid not null references startups(id) on delete cascade,
  target_startup_id uuid not null references startups(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  created_at timestamptz not null default now(),
  unique (requesting_startup_id, target_startup_id)
);

alter table startup_collaborations enable row level security;

drop policy if exists "Either side reads their collaborations" on startup_collaborations;
create policy "Either side reads their collaborations" on startup_collaborations
  for select using (
    exists (
      select 1 from startups s
      where (s.id = startup_collaborations.requesting_startup_id or s.id = startup_collaborations.target_startup_id)
        and s.owner_user_id = auth.uid()
    )
  );
